#!/data/data/com.termux/files/usr/bin/bash
# Deploy the day-to-day runtime scripts to Termux $HOME:
#
#   ~/start-x11.sh        Launch the whole desktop:
#                           - kick the Termux:X11 Android app via `am start`
#                           - start a Termux-side X11 + pulseaudio
#                           - open a proot session as the user and run i3
#   ~/start-proot.sh      Drop into a proot Ubuntu shell as the configured user
#                         (no X11 — just a Linux terminal session).
#   ~/stop-x11.sh         Tear it all down (kill i3 inside proot, stop the X
#                         server, the Termux:X11 activity stays for re-use).
#   ~/proot.env           Small env file the above scripts source so values
#                         stay in sync with what 04/05 used.
#
# Re-running overwrites the deployed scripts (keeps a .bak copy of each).
# Edits you make to deployed scripts go away on re-run; edit this script
# (or its embedded heredocs) for persistent changes.
#
# Env overrides:
#   PROOT_DISTRO     default: ubuntu
#   PROOT_USER       default: ryno
#   DISPLAY_NUM      default: 0          (Termux:X11 listens on :0 by default)
#   START_PULSE      default: 1          set 0 to skip pulseaudio

set -euo pipefail

PROOT_DISTRO="${PROOT_DISTRO:-ubuntu}"
PROOT_USER="${PROOT_USER:-ryno}"
DISPLAY_NUM="${DISPLAY_NUM:-0}"
START_PULSE="${START_PULSE:-1}"
USE_XAUTH="${USE_XAUTH:-0}"
PUBUNTU_SSH_PORT="${PUBUNTU_SSH_PORT:-9923}"
PUBUNTU_SSH_USER="${PUBUNTU_SSH_USER:-ryno}"

log()  { printf '\033[1;34m[deploy-runtime]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*"; }

# ---- 0. Termux-side prereqs (the runtime scripts need these) -------------
# DroidDesk's "Mesa Zink Core" + "Vulkan Loader" step came down to a handful
# of Termux packages from x11-repo. Without them the X server (Termux:X11)
# and any Termux-native graphical app fall back to all-software rendering,
# which is the perceived video-stutter problem on PowerVR.
#
# Notes per package:
#   mesa                          OpenGL implementation (includes Zink)
#   vulkan-loader-android         Vulkan ICD loader, Android-specific build
#   mesa-vulkan-icd-swrast        Software Vulkan (lavapipe). PowerVR DXT has
#                                 no Mesa Vulkan ICD (PVR driver is Rogue-only),
#                                 so swrast is the workable fallback Vulkan.
#   virglrenderer-android         GL-over-virgl backend Termux:X11 can use
#                                 for GPU-rendered windows.
#   xorg-xrandr                   Resolution control (e.g. for external display).
#
# Env knobs:
#   START_PULSE             default 1   include pulseaudio (~/start-x11.sh uses it)
#   INSTALL_TERMUX_FIREFOX  default 0   ALSO install Termux-native firefox as
#                                       a smoother alternative to proot-firefox
#                                       (this is what DroidDesk's "smooth video"
#                                       experience was actually using). Launch
#                                       from a Termux shell with DISPLAY=:0.
log "[0/4] installing Termux-side prereqs (X11, Mesa, Vulkan loader, virgl)"
pkg install -y x11-repo >/dev/null 2>&1 || true

# vulkan-loader-generic and vulkan-loader-android collide (both ship libvulkan.so).
# We want the -android one (hooks into Android's Vulkan layer, can reach
# vulkan.powervr.so). If the generic build is sitting there from a transitive
# dep, swap it for the android variant.
if dpkg -s vulkan-loader-generic >/dev/null 2>&1 \
        && ! dpkg -s vulkan-loader-android >/dev/null 2>&1; then
    log "    swapping vulkan-loader-generic → vulkan-loader-android"
    pkg uninstall -y vulkan-loader-generic >/dev/null 2>&1 || true
fi

TERMUX_PKGS="termux-x11-nightly mesa vulkan-loader-android mesa-vulkan-icd-swrast virglrenderer-android xorg-xrandr socat"
[ "${START_PULSE:-1}" = "1" ]            && TERMUX_PKGS="$TERMUX_PKGS pulseaudio"
[ "${INSTALL_TERMUX_FIREFOX:-0}" = "1" ] && TERMUX_PKGS="$TERMUX_PKGS firefox"

for p in $TERMUX_PKGS; do
    if ! dpkg -s "$p" >/dev/null 2>&1; then
        pkg install -y "$p" >/dev/null 2>&1 || warn "    pkg install $p failed (continuing)"
    fi
done

write_with_backup() {
    local path="$1"
    [ -f "$path" ] && cp "$path" "$path.bak"
    cat > "$path"
    chmod +x "$path"
}

# ---- 1. proot.env (sourced by the other scripts) ---------------------------
log "[1/4] writing ~/proot.env"
write_with_backup "$HOME/proot.env" <<EOF
# Generated by pixel/termux/06-deploy-runtime-scripts.sh — DO NOT edit manually;
# re-run the deploy script if these need to change.
export PROOT_DISTRO="$PROOT_DISTRO"
export PROOT_USER="$PROOT_USER"
export DISPLAY_NUM="$DISPLAY_NUM"
export START_PULSE="$START_PULSE"
# X11 auth — set USE_XAUTH=1 to start Termux:X11 with magic-cookie auth
# instead of -ac (no auth). Cookies are written to ~/.Xauthority and
# auto-synced to pubuntu over SSH (best-effort) if reachable.
# See pixel/docs/pixel-desktop-architecture.md (security section).
export USE_XAUTH="$USE_XAUTH"
export PUBUNTU_SSH_PORT="$PUBUNTU_SSH_PORT"
export PUBUNTU_SSH_USER="$PUBUNTU_SSH_USER"
EOF

# ---- 2. start-proot.sh — terminal-only entry into the proot Linux env ------
log "[2/4] writing ~/start-proot.sh"
write_with_backup "$HOME/start-proot.sh" <<'EOF'
#!/data/data/com.termux/files/usr/bin/bash
# Drop into the proot Ubuntu shell as the configured user.
# Pass extra args to forward them to bash inside proot, e.g.:
#   ./start-proot.sh -c "uname -a"
set -euo pipefail
source ~/proot.env
exec proot-distro login "$PROOT_DISTRO" --user "$PROOT_USER" -- bash --login "$@"
EOF

# ---- 3. start-x11.sh — fire up everything for a GUI session ----------------
log "[3/4] writing ~/start-x11.sh"
write_with_backup "$HOME/start-x11.sh" <<'EOF'
#!/data/data/com.termux/files/usr/bin/bash
# Bring up the GUI stack:
#   1. Make sure the Termux:X11 Android app is running (foreground its activity).
#   2. Start a Termux-side X11 listener on :$DISPLAY_NUM (-ac = no auth).
#   3. (Optional) start pulseaudio for sound.
#   4. Start a socat bridge so VM/LXC clients (e.g. pubuntu in Podroid)
#      can reach Termux:X11 directly over TCP — bypasses SSH X-forward
#      and gives ~14x throughput. Bound ONLY to the AVF TAP interface
#      so it's not exposed on Wi-Fi / Tailscale / etc.
#      (See pixel/docs/pixel-desktop-architecture.md "Measured 2026-05-29".)
#   5. Enter the proot Ubuntu rootfs and exec i3 (via .xinitrc).
#
# Logs:
#   /tmp/termux-x11.log     X server output
#   /tmp/socat_x11.log      direct-X bridge log
#   /tmp/proot-i3.log       i3 + apps output
#
# Stop with:  bash ~/stop-x11.sh
set -uo pipefail
source ~/proot.env
LOG_DIR="${TMPDIR:-/data/data/com.termux/files/usr/tmp}"
mkdir -p "$LOG_DIR"

# 1. foreground the Termux:X11 activity so the X server has a Surface
if command -v am >/dev/null 2>&1; then
    am start --user 0 -n com.termux.x11/.MainActivity >/dev/null 2>&1 || true
fi

# 2. X11 auth setup (idempotent — keeps existing cookie across restarts)
#    USE_XAUTH=1 → run with magic-cookie auth (-auth ~/.Xauthority)
#    USE_XAUTH=0 → run with no auth (-ac); only safe because socat is bound
#                  to AVF TAP and that subnet is your own VMs only.
XAUTH_FILE="$HOME/.Xauthority"
AVF_TAP_IP=$(ifconfig avf_tap_fixed 2>/dev/null | awk '/inet / {print $2}' | head -1)
if [ "$USE_XAUTH" = "1" ]; then
    if [ ! -s "$XAUTH_FILE" ] || ! xauth -f "$XAUTH_FILE" list 2>/dev/null \
            | grep -q "MIT-MAGIC-COOKIE-1"; then
        echo "[start-x11] generating new xauth cookie → $XAUTH_FILE"
        COOKIE=$(openssl rand -hex 16 2>/dev/null || \
                 dd if=/dev/urandom bs=16 count=1 2>/dev/null | xxd -p -c 32)
        rm -f "$XAUTH_FILE"
        touch "$XAUTH_FILE"
        chmod 600 "$XAUTH_FILE"
        # Add an entry per address the X server can be reached at:
        # - local Unix socket (Termux processes)
        # - AVF TAP IP (pubuntu/Alpine connecting via socat)
        xauth -f "$XAUTH_FILE" add ":$DISPLAY_NUM"          . "$COOKIE"
        if [ -n "$AVF_TAP_IP" ]; then
            xauth -f "$XAUTH_FILE" add "$AVF_TAP_IP:$DISPLAY_NUM" . "$COOKIE"
        fi
    else
        echo "[start-x11] reusing existing xauth cookie in $XAUTH_FILE"
    fi
    X11_AUTH_FLAGS="-auth $XAUTH_FILE"
else
    X11_AUTH_FLAGS="-ac"
fi

# Start the X server (kill any old one on this display first)
if pgrep -f "termux-x11 :$DISPLAY_NUM" >/dev/null 2>&1; then
    echo "[start-x11] X server already running on :$DISPLAY_NUM"
else
    echo "[start-x11] starting Termux:X11 on :$DISPLAY_NUM ($X11_AUTH_FLAGS)"
    nohup termux-x11 ":$DISPLAY_NUM" $X11_AUTH_FLAGS \
        >"$LOG_DIR/termux-x11.log" 2>&1 &
    sleep 1
fi

# 2b. Sync cookie to pubuntu (best-effort) so the user doesn't have to.
#     Quiet failure if pubuntu's SSH isn't reachable yet.
if [ "$USE_XAUTH" = "1" ] && [ -n "$AVF_TAP_IP" ] \
        && command -v nc >/dev/null 2>&1 && nc -z -w 2 localhost "$PUBUNTU_SSH_PORT" 2>/dev/null; then
    echo "[start-x11] deploying xauth cookie to pubuntu (best-effort)"
    if xauth -f "$XAUTH_FILE" extract - "$AVF_TAP_IP:$DISPLAY_NUM" 2>/dev/null \
            | ssh -p "$PUBUNTU_SSH_PORT" -o BatchMode=yes -o ConnectTimeout=3 \
                  "${PUBUNTU_SSH_USER}@localhost" \
                  "touch ~/.Xauthority; chmod 600 ~/.Xauthority; xauth -f ~/.Xauthority merge -" \
            2>/dev/null; then
        echo "[start-x11]   cookie deployed to pubuntu's ~/.Xauthority"
    else
        echo "[start-x11]   couldn't reach pubuntu over SSH (run ~/sync-x11-cookie.sh manually later)"
    fi
fi

# 3. pulseaudio (best-effort)
if [ "$START_PULSE" = "1" ] && command -v pulseaudio >/dev/null 2>&1; then
    if ! pgrep -x pulseaudio >/dev/null 2>&1; then
        echo "[start-x11] starting pulseaudio"
        pulseaudio --start --exit-idle-time=-1 --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" >/dev/null 2>&1 || true
    fi
fi

# 4. direct-X-over-TCP bridge (for pubuntu / Alpine to bypass slow ssh -Y)
# Only useful when Podroid AVF VM is up (so the avf_tap_fixed interface exists).
# Bind specifically to that interface so the port is reachable from inside
# the VM only — NOT from LAN, Tailscale, cellular, or other Android apps.
AVF_TAP_IP=$(ifconfig avf_tap_fixed 2>/dev/null | awk '/inet / {print $2}' | head -1)
X_SOCK="$PREFIX/tmp/.X11-unix/X${DISPLAY_NUM}"
if [ -n "$AVF_TAP_IP" ] && [ -S "$X_SOCK" ] && command -v socat >/dev/null 2>&1; then
    if pgrep -f "socat TCP-LISTEN:6000" >/dev/null 2>&1; then
        echo "[start-x11] direct-X bridge already running on $AVF_TAP_IP:6000"
    else
        echo "[start-x11] starting direct-X bridge on $AVF_TAP_IP:6000 → $X_SOCK"
        nohup socat TCP-LISTEN:6000,fork,reuseaddr,bind=$AVF_TAP_IP \
                    UNIX-CONNECT:$X_SOCK \
            </dev/null >>"$LOG_DIR/socat_x11.log" 2>&1 &
        disown $!
        echo "[start-x11]   from pubuntu/Alpine, set:  export DISPLAY=$AVF_TAP_IP:0"
    fi
elif [ -z "$AVF_TAP_IP" ]; then
    echo "[start-x11] no avf_tap_fixed interface (Podroid VM not running) — skipping direct-X bridge"
elif ! command -v socat >/dev/null 2>&1; then
    echo "[start-x11] socat not installed — skipping direct-X bridge ('pkg install socat' to enable)"
fi

# 5. enter proot, run i3 via the user's ~/.xinitrc
echo "[start-x11] launching i3 inside $PROOT_DISTRO as $PROOT_USER"
echo "[start-x11] tail -f $LOG_DIR/proot-i3.log  for desktop logs"
proot-distro login "$PROOT_DISTRO" --user "$PROOT_USER" --shared-tmp -- \
    bash --login -c "export DISPLAY=:$DISPLAY_NUM; export PULSE_SERVER=tcp:127.0.0.1; exec ~/.xinitrc" \
    >"$LOG_DIR/proot-i3.log" 2>&1 &
disown $!

echo "[start-x11] all started. Switch to the Termux:X11 app to see the desktop."
EOF

# ---- 3b. sync-x11-cookie.sh — push Termux's xauth cookie to pubuntu --------
log "[3b/4] writing ~/sync-x11-cookie.sh"
write_with_backup "$HOME/sync-x11-cookie.sh" <<'EOF'
#!/data/data/com.termux/files/usr/bin/bash
# Push Termux's xauth cookie (from ~/.Xauthority) into pubuntu's
# ~/.Xauthority so pubuntu X clients authenticate against Termux:X11
# without -ac being set on the X server.
#
# Run after start-x11.sh has generated a cookie (USE_XAUTH=1). The
# auto-deploy in start-x11.sh tries this on every start; this script
# is for when:
#   - pubuntu wasn't reachable at start-x11 time
#   - you rebuilt pubuntu and need to push the cookie again
#   - you rotated the cookie (rm ~/.Xauthority then re-run start-x11.sh)
#
# Env:
#   PUBUNTU_SSH_HOST     default: localhost  (Podroid forward to pubuntu)
#   PUBUNTU_SSH_PORT     default: 9923
#   PUBUNTU_SSH_USER     default: ryno
#   DISPLAY_NUM          default: 0
set -euo pipefail
source ~/proot.env
PUBUNTU_SSH_HOST="${PUBUNTU_SSH_HOST:-localhost}"

XAUTH_FILE="$HOME/.Xauthority"
if [ ! -s "$XAUTH_FILE" ]; then
    echo "[sync-x11-cookie] $XAUTH_FILE is empty/missing — run start-x11.sh with USE_XAUTH=1 first" >&2
    exit 1
fi

AVF_TAP_IP=$(ifconfig avf_tap_fixed 2>/dev/null | awk '/inet / {print $2}' | head -1)
if [ -z "$AVF_TAP_IP" ]; then
    echo "[sync-x11-cookie] avf_tap_fixed interface not present — is Podroid running?" >&2
    exit 1
fi

ENTRY="$AVF_TAP_IP:$DISPLAY_NUM"
if ! xauth -f "$XAUTH_FILE" list "$ENTRY" 2>/dev/null | grep -q "MIT-MAGIC-COOKIE-1"; then
    echo "[sync-x11-cookie] no cookie for $ENTRY in $XAUTH_FILE" >&2
    echo "[sync-x11-cookie] start-x11.sh with USE_XAUTH=1 should have created one" >&2
    exit 1
fi

echo "[sync-x11-cookie] pushing $ENTRY cookie → ${PUBUNTU_SSH_USER}@${PUBUNTU_SSH_HOST}:${PUBUNTU_SSH_PORT}"
xauth -f "$XAUTH_FILE" extract - "$ENTRY" \
    | ssh -p "$PUBUNTU_SSH_PORT" -o ConnectTimeout=5 \
          "${PUBUNTU_SSH_USER}@${PUBUNTU_SSH_HOST}" \
          'touch ~/.Xauthority; chmod 600 ~/.Xauthority; xauth -f ~/.Xauthority merge -'
echo "[sync-x11-cookie] done. Verify in pubuntu with:"
echo "    ssh -p $PUBUNTU_SSH_PORT $PUBUNTU_SSH_USER@$PUBUNTU_SSH_HOST 'DISPLAY=$ENTRY xset q' | head -3"
EOF

# ---- 4. stop-x11.sh --------------------------------------------------------
log "[4/4] writing ~/stop-x11.sh"
write_with_backup "$HOME/stop-x11.sh" <<'EOF'
#!/data/data/com.termux/files/usr/bin/bash
# Tear down the GUI session. We DON'T stop the Termux:X11 Android
# activity itself (cheap to leave running, faster restart next time).
set -uo pipefail
source ~/proot.env

# 1. tell i3 to exit cleanly (gives apps a chance to save state)
echo "[stop-x11] asking i3 to exit"
proot-distro login "$PROOT_DISTRO" --user "$PROOT_USER" --shared-tmp -- \
    bash -c "export DISPLAY=:$DISPLAY_NUM; i3-msg exit" >/dev/null 2>&1 || true
sleep 1

# 2. kill anything still inside proot that's holding the display
echo "[stop-x11] killing proot processes still on DISPLAY=:$DISPLAY_NUM"
pkill -f "proot-distro login .* $PROOT_DISTRO" 2>/dev/null || true
pkill -f "DISPLAY=:$DISPLAY_NUM" 2>/dev/null || true

# 3. stop the direct-X bridge if it was running
if pgrep -f "socat TCP-LISTEN:6000" >/dev/null 2>&1; then
    echo "[stop-x11] stopping direct-X bridge (socat on :6000)"
    pkill -f "socat TCP-LISTEN:6000" 2>/dev/null || true
fi

# 4. stop the X server
echo "[stop-x11] stopping Termux:X11 listener on :$DISPLAY_NUM"
pkill -f "termux-x11 :$DISPLAY_NUM" 2>/dev/null || true

# 5. (optional) stop pulseaudio
if [ "$START_PULSE" = "1" ] && pgrep -x pulseaudio >/dev/null 2>&1; then
    pulseaudio -k 2>/dev/null || true
fi

echo "[stop-x11] done."
EOF

log ""
log "Deployed runtime scripts to \$HOME:"
log "    ~/start-proot.sh        terminal-only shell into proot Ubuntu"
log "    ~/start-x11.sh          bring up Termux:X11 + direct-X bridge + i3 desktop"
log "    ~/stop-x11.sh           tear down the desktop"
log "    ~/sync-x11-cookie.sh    (re)deploy xauth cookie to pubuntu when USE_XAUTH=1"
log "    ~/proot.env             shared config (PROOT_DISTRO, PROOT_USER, USE_XAUTH, ...)"
log ""
log "First-time GUI run:"
log "    bash ~/start-x11.sh"
log "    # then switch to the Termux:X11 app on the phone — i3 should appear"
log ""
log "Useful Termux-X11 app settings (top-left hamburger menu):"
log "    - 'Show additional keys'     keyboard helper bar (Tab, Ctrl, Esc, …)"
log "    - 'Force fullscreen'         hides the Android nav bar"
log "    - 'Pointer capture'          relative mouse for X (gaming/CAD)"
