#!/data/data/com.termux/files/usr/bin/bash
# Deploy the day-to-day runtime scripts to Termux $HOME:
#
#   ~/start-x11.sh        Launch the whole desktop:
#                           - kick the Termux:X11 Android app via `am start`
#                           - start a Termux-side X11 + pulseaudio
#                           - open a proot session as the user and run i3
#   ~/start-proot.sh      Drop into a proot Ubuntu shell as the configured user
#                         (no X11 — just a Linux terminal session).
#   ~/stop-x11.sh         Tear it all down (kill i3 inside proot, stop the X
#                         server, the Termux:X11 activity stays for re-use).
#   ~/proot.env           Small env file the above scripts source so values
#                         stay in sync with what 04/05 used.
#
# Re-running overwrites the deployed scripts (keeps a .bak copy of each).
# Edits you make to deployed scripts go away on re-run; edit this script
# (or its embedded heredocs) for persistent changes.
#
# Env overrides:
#   PROOT_DISTRO     default: ubuntu
#   PROOT_USER       default: ryno
#   DISPLAY_NUM      default: 0          (Termux:X11 listens on :0 by default)
#   START_PULSE      default: 1          set 0 to skip pulseaudio

set -euo pipefail

PROOT_DISTRO="${PROOT_DISTRO:-ubuntu}"
PROOT_USER="${PROOT_USER:-ryno}"
DISPLAY_NUM="${DISPLAY_NUM:-0}"
START_PULSE="${START_PULSE:-1}"

log()  { printf '\033[1;34m[deploy-runtime]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*"; }

write_with_backup() {
    local path="$1"
    [ -f "$path" ] && cp "$path" "$path.bak"
    cat > "$path"
    chmod +x "$path"
}

# ---- 1. proot.env (sourced by the other scripts) ---------------------------
log "[1/4] writing ~/proot.env"
write_with_backup "$HOME/proot.env" <<EOF
# Generated by pixel/termux/06-deploy-runtime-scripts.sh — DO NOT edit manually;
# re-run the deploy script if these need to change.
export PROOT_DISTRO="$PROOT_DISTRO"
export PROOT_USER="$PROOT_USER"
export DISPLAY_NUM="$DISPLAY_NUM"
export START_PULSE="$START_PULSE"
EOF

# ---- 2. start-proot.sh — terminal-only entry into the proot Linux env ------
log "[2/4] writing ~/start-proot.sh"
write_with_backup "$HOME/start-proot.sh" <<'EOF'
#!/data/data/com.termux/files/usr/bin/bash
# Drop into the proot Ubuntu shell as the configured user.
# Pass extra args to forward them to bash inside proot, e.g.:
#   ./start-proot.sh -c "uname -a"
set -euo pipefail
source ~/proot.env
exec proot-distro login "$PROOT_DISTRO" --user "$PROOT_USER" -- bash --login "$@"
EOF

# ---- 3. start-x11.sh — fire up everything for a GUI session ----------------
log "[3/4] writing ~/start-x11.sh"
write_with_backup "$HOME/start-x11.sh" <<'EOF'
#!/data/data/com.termux/files/usr/bin/bash
# Bring up the GUI stack:
#   1. Make sure the Termux:X11 Android app is running (foreground its activity).
#   2. Start a Termux-side X11 listener on :$DISPLAY_NUM (-ac = no auth).
#   3. (Optional) start pulseaudio for sound.
#   4. Enter the proot Ubuntu rootfs and exec i3 (via .xinitrc).
#
# Logs:
#   /tmp/termux-x11.log     X server output
#   /tmp/proot-i3.log       i3 + apps output
#
# Stop with:  bash ~/stop-x11.sh
set -uo pipefail
source ~/proot.env
LOG_DIR="${TMPDIR:-/data/data/com.termux/files/usr/tmp}"
mkdir -p "$LOG_DIR"

# 1. foreground the Termux:X11 activity so the X server has a Surface
if command -v am >/dev/null 2>&1; then
    am start --user 0 -n com.termux.x11/.MainActivity >/dev/null 2>&1 || true
fi

# 2. start the X server (kill any old one on this display first)
if pgrep -f "termux-x11 :$DISPLAY_NUM" >/dev/null 2>&1; then
    echo "[start-x11] X server already running on :$DISPLAY_NUM"
else
    echo "[start-x11] starting Termux:X11 on :$DISPLAY_NUM"
    nohup termux-x11 ":$DISPLAY_NUM" -ac >"$LOG_DIR/termux-x11.log" 2>&1 &
    sleep 1
fi

# 3. pulseaudio (best-effort)
if [ "$START_PULSE" = "1" ] && command -v pulseaudio >/dev/null 2>&1; then
    if ! pgrep -x pulseaudio >/dev/null 2>&1; then
        echo "[start-x11] starting pulseaudio"
        pulseaudio --start --exit-idle-time=-1 --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" >/dev/null 2>&1 || true
    fi
fi

# 4. enter proot, run i3 via the user's ~/.xinitrc
echo "[start-x11] launching i3 inside $PROOT_DISTRO as $PROOT_USER"
echo "[start-x11] tail -f $LOG_DIR/proot-i3.log  for desktop logs"
proot-distro login "$PROOT_DISTRO" --user "$PROOT_USER" --shared-tmp -- \
    bash --login -c "export DISPLAY=:$DISPLAY_NUM; export PULSE_SERVER=tcp:127.0.0.1; exec ~/.xinitrc" \
    >"$LOG_DIR/proot-i3.log" 2>&1 &
disown $!

echo "[start-x11] all started. Switch to the Termux:X11 app to see the desktop."
EOF

# ---- 4. stop-x11.sh --------------------------------------------------------
log "[4/4] writing ~/stop-x11.sh"
write_with_backup "$HOME/stop-x11.sh" <<'EOF'
#!/data/data/com.termux/files/usr/bin/bash
# Tear down the GUI session. We DON'T stop the Termux:X11 Android
# activity itself (cheap to leave running, faster restart next time).
set -uo pipefail
source ~/proot.env

# 1. tell i3 to exit cleanly (gives apps a chance to save state)
echo "[stop-x11] asking i3 to exit"
proot-distro login "$PROOT_DISTRO" --user "$PROOT_USER" --shared-tmp -- \
    bash -c "export DISPLAY=:$DISPLAY_NUM; i3-msg exit" >/dev/null 2>&1 || true
sleep 1

# 2. kill anything still inside proot that's holding the display
echo "[stop-x11] killing proot processes still on DISPLAY=:$DISPLAY_NUM"
pkill -f "proot-distro login .* $PROOT_DISTRO" 2>/dev/null || true
pkill -f "DISPLAY=:$DISPLAY_NUM" 2>/dev/null || true

# 3. stop the X server
echo "[stop-x11] stopping Termux:X11 listener on :$DISPLAY_NUM"
pkill -f "termux-x11 :$DISPLAY_NUM" 2>/dev/null || true

# 4. (optional) stop pulseaudio
if [ "$START_PULSE" = "1" ] && pgrep -x pulseaudio >/dev/null 2>&1; then
    pulseaudio -k 2>/dev/null || true
fi

echo "[stop-x11] done."
EOF

log ""
log "Deployed runtime scripts to \$HOME:"
log "    ~/start-proot.sh    terminal-only shell into proot Ubuntu"
log "    ~/start-x11.sh      bring up Termux:X11 + i3 desktop"
log "    ~/stop-x11.sh       tear down the desktop"
log "    ~/proot.env         shared config (PROOT_DISTRO, PROOT_USER, etc.)"
log ""
log "First-time GUI run:"
log "    bash ~/start-x11.sh"
log "    # then switch to the Termux:X11 app on the phone — i3 should appear"
log ""
log "Useful Termux-X11 app settings (top-left hamburger menu):"
log "    - 'Show additional keys'     keyboard helper bar (Tab, Ctrl, Esc, …)"
log "    - 'Force fullscreen'         hides the Android nav bar"
log "    - 'Pointer capture'          relative mouse for X (gaming/CAD)"
